# 启动端口号
server:
  post: 8001

# MySQL数据源配置
mysql:
  username: root      # 修改为自己数据库的用户名
  password: 123456    # 修改为自己数据库的密码
  url: tcp(110.40.208.203:3306)/gin_blog?charset=utf8&parseTime=True&loc=Local
